version: "3"
services:

  fpm:
#    image: bd43c5a57b5b
    build: php
    links:
      - web
      - db

  db:
    image: mariadb:10.4
#    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  web:
#    image: 28837dd55309
    build: web
#    volumes:
#      - ~/www:/var/www/html
    ports:
      - "8099:80"
#    restart: always
    links:
      - db

  tools:
#    image: d064f46edf63
    build: tools
    links:
      - db
      - web

volumes:
  db: ~
