version: "3.7"
services:
  php:
    build: ./docker/php
    env_file: docker.env
    volumes:
      - $SSH_AUTH_SOCK:/tmp/agent.sock
      - ~/.composer:/home/.composer
      - ./docker/config/bashrc:/home/.bashrc
      - ./docker/config/bash_aliases:/home/.bash_aliases
      - ./docker/config/inputrc:/home/.inputrc
      - ./docker/data/history:/home/.bash_history
      - ./:/srv/
